### ISSUE TITLE
Excuse for npm package name

### ISSUE THREAD

**Issue by noraesae** [scottcorgan/pen#1]
Hello,

I am a contributor of [another project named `pen`](https://github.com/noraesae/pen). It is a markdown previewer in command line, and I thought `pen` is an appropriate name for it.

I am currently using [scoped package](https://docs.npmjs.com/getting-started/scoped-packages) to name it as `@noraesae/pen`. However, it is somewhat verbose. I would be really happy if `pen` can be used as its npm package name.

I found that you might use [`bat`](https://www.npmjs.com/package/bat) for the same package. I would like to carefully ask if you would mind yielding the name, `pen`? I think it can be done by transferring ownership of the package.

- `npm owner add noraesae pen`
- `npm owner rm scottcorgan pen`

I will throughly appreciate if you do not mind. I promise I will maintain the package seriously.

Please let me know if there is any comment.
Thanks in advance.

Best regards,
Jun

**Comment by scottcorgan** [comment]
Sure, done!
